# Generated by Django 3.1.7 on 2021-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='pago',
            field=models.ImageField(blank=True, null=True, upload_to='pagos/', verbose_name='imagen del pago'),
        ),
    ]
