# Generated by Django 3.1.7 on 2021-09-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_hora_evento',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
