# Generated by Django 3.1.7 on 2021-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20211023_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
