# Generated by Django 3.2.7 on 2021-09-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_rol_de_usuario_usuario_roldeusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='roldeusuario',
            new_name='rol_de_usuario',
        ),
    ]
