# Generated by Django 3.2.7 on 2021-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20210911_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='gelionz.png', upload_to=''),
        ),
    ]
