# Generated by Django 3.1.7 on 2021-09-18 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210917_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='perfil_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.profile'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profile'),
        ),
    ]
