# Generated by Django 3.1.7 on 2021-09-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='imagen de perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('rol_de_usuario', models.CharField(choices=[('jugador', 'Jugador'), ('streaming', 'Streaming')], default='jugador', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capitan', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_equipo', models.CharField(max_length=80)),
                ('num_integrantes', models.IntegerField(blank=True, null=True)),
                ('eventos_jugados', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('partida', 'partida'), ('torneo', 'Torneo')], max_length=200)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('valor_evento', models.PositiveIntegerField()),
                ('ganador_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_jugadores', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('cancelado', 'Cancelado'), ('reportado', 'Reportado'), ('terminado', 'Terminado')], default='disponible', max_length=200)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('jugador', 'Jugador'), ('streamer', 'Streamer')], max_length=200)),
                ('fecha_hora_pago', models.DateTimeField()),
                ('valor_pago', models.IntegerField()),
                ('inscripcion_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('es_ganador', models.CharField(choices=[('inscrito', 'inscrito'), ('ganador', 'ganador'), ('perdedor', 'perdedor'), ('pendiente', 'pendiente')], default='inscrito', max_length=50)),
                ('is_paid', models.BooleanField(default=True)),
                ('id_equipo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
                ('inscripcion_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Fraude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fraude', models.CharField(max_length=200)),
                ('fecha_hora_fraude', models.DateTimeField(auto_now_add=True)),
                ('descripsion', models.CharField(max_length=200)),
                ('fraude_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=11)),
                ('entidad', models.CharField(max_length=80)),
                ('perfil_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
