# Generated by Django 3.2.7 on 2021-09-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210910_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_de_usuario',
            new_name='roldeusuario',
        ),
    ]
