# Generated by Django 3.2.7 on 2021-09-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20210911_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('partida', 'partida'), ('torneo', 'Torneo')], max_length=200)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('valor_evento', models.PositiveIntegerField()),
                ('ganador_evento', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_jugadores', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('cancelado', 'Cancelado'), ('reportado', 'Reportado'), ('terminado', 'Terminado')], default='disponible', max_length=200)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profile')),
            ],
        ),
    ]
