# Generated by Django 3.2.7 on 2021-09-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210911_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capitan', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_equipo', models.CharField(max_length=80)),
                ('num_integrantes', models.IntegerField(blank=True, null=True)),
                ('eventos_jugados', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.equipo')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('jugador', 'Jugador'), ('streamer', 'Streamer')], max_length=200)),
                ('fecha_hora_pago', models.DateTimeField()),
                ('valor_pago', models.IntegerField()),
                ('inscripcion_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('es_ganador', models.CharField(choices=[('inscrito', 'inscrito'), ('ganador', 'ganador'), ('perdedor', 'perdedor'), ('pendiente', 'pendiente')], default='inscrito', max_length=50)),
                ('is_paid', models.BooleanField(default=True)),
                ('id_equipo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.equipo')),
                ('inscripcion_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Fraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fraude', models.CharField(max_length=200)),
                ('fecha_hora_fraude', models.DateTimeField(auto_now_add=True)),
                ('descripsion', models.CharField(max_length=200)),
                ('fraude_evento_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=11)),
                ('entidad', models.CharField(max_length=80)),
                ('perfil_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.profile')),
            ],
        ),
    ]
