# Generated by Django 3.2.7 on 2021-09-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_cuenta_equipo_fraude_inscripcion_pago_user_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('rol_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.rol')),
                ('user_FK', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='perfil_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.perfil'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.perfil'),
        ),
        migrations.AlterField(
            model_name='user_equipo',
            name='user_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.perfil'),
        ),
    ]
