# Generated by Django 3.1.7 on 2021-09-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20210915_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
