# Generated by Django 3.1.7 on 2021-09-18 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20210917_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='perfil_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fraude',
            name='fraude_evento_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='inscripcion_evento_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.evento'),
        ),
        migrations.AlterField(
            model_name='user_equipo',
            name='equipo_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.equipo'),
        ),
        migrations.AlterField(
            model_name='user_equipo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
